### PR TITLE
create relationship gcpsql instance vpc network

### PR DESCRIPTION
**Pull request by sagarnavale**

### CODE REVIEW

**Review by ajinkya1986 — APPROVED** [review]
Looks good

**Review by ganeshjagdale9545 — CHANGES_REQUESTED** [review]
Implement public facing analysis jobs for sql instance and its attached resources

**Comment by ganeshjagdale9545** [comment]
@sagarnavale also update inventory for public ip

**Comment by mpurusottamc** [comment]
@sagarnavale can you fix this?

**Review by mpurusottamc — COMMENTED** [review]
looks good. can you add test cases?

**Comment by mpurusottamc** [comment]
@sagarnavale also, please resolve the conflict.

**Review by mpurusottamc — APPROVED** [review]
looks good.

**Pull request merged**
