### PR TITLE
Added logic to create nodes for Ranges (Ipv4 and Ipv6)

### PR DESCRIPTION
**Pull request by sash-21**

### CODE REVIEW

**Review by ganeshjagdale9545 — CHANGES_REQUESTED** [review]
@sash-21 make the changes as we have discussed in the call

**Comment by mpurusottamc** [comment]
@sash-21 are the changes completed?

**Comment by sash-21** [comment]
@ganeshjagdale9545 @mpurusottamc 
- I have handled the case if the list of IP ranges is not present then allocate the single IP present in the list as discussed in the call.
- I didn't got any separating factor that tells if it is an Ipv4 or Ipv6 addredd so currently the nodes will be formed with the label `IpRange`

Changes Made

**Comment by sash-21** [comment]
@ganeshjagdale9545 changes done as discussed, I have added another helper that checks if a valid IP is present or it is a cloud resources, * values etc then directly stored as Ipv4

**Review by ganeshjagdale9545 — APPROVED** [review]
Looks good to me

**Review by mpurusottamc — APPROVED** [review]
lgtm

**Pull request merged**
