### PR TITLE
implement threading for azure services

### PR DESCRIPTION
**Pull request by ganeshjagdale9545**

### CODE REVIEW

**Review by mpurusottamc — COMMENTED** [review]
looks good. can you add your testing results?
how did you test, what was the earlier timing vs current timing, etc?

**Comment by ganeshjagdale9545** [comment]
Without threading execution time
`--- execution time: 133.8629229068756 seconds ---`
With threading execution time
`--- execution time: 89.83109712600708 seconds ---`

**Comment by ganeshjagdale9545** [comment]
For testing use main.py file
`import sys
import logging
import cartography.cli
import time


logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


def run_azure():
    body = {
        "azure": {
            "tenant_id": "0163ec55-222f-4d40-806a.....................",
            "client_id": 'fe03f209-eede-47ef-887b....................',
            "client_secret": '7ParBgS.......................',
            "redirect_uri": 'http://localhost/MyApp',  # https://console.cloudanix.com/v1/azurewebhook/install
            "subscription_id": "5592e8dc-541e-4e4b.....................",
            "refresh_token": 'zb9w5bS_VkheCILppO1Pjkg5CEAfQakgj1h1m......................',
            "graph_scope": 'https://graph.windows.net/Directory.Read.All',
            "azure_scope": 'openid profile email offline_access https://management.azure.com/user_impersonation'
        },
        "neo4j": {
            "uri": 'bolt://127.0.0.1:7687',
            "user": '',
            "pwd": ''
        },
        "logging": {
            "mode": 'verbose'
        },
        "params": {
            "sessionString": "1ba87a0b25564191.....................",
            "eventId": "e5c16b8afd0b6dd8743b..................",
            "templateType": "AZUREINVENTORYVIEWS",
            "workspace": {
                "id_string": "1ebdbb12ca1ed6d1..................",
                "name": "Azure QA Environment",
                "account_id": "1cd3dcd9-06fa-4f1d................."
            },
        }
    }
    start_time = time.time()
    resp = cartography.cli.run_azure(body)
    print("--- execution time: %s seconds ---" % (time.time() - start_time))

    if 'status' in resp and resp['status'] == 'success':
        logger.info(f'success response from cartography: {resp}')

    else:
        logger.info(f'failed to process cartography: {resp["message"]}')

    sys.exit()


if __name__ == '__main__':
    # sys.exit(cartography.cli.main())

    run_azure()`

**Comment by mpurusottamc** [comment]
Looks good to me. Thanks for sharing the results.

**Pull request merged**
